network_bond_interfaces:
    - device: "{{ bonded_interface }}" 
      bootproto: "static"
      onboot: "yes"
      nm_controlled: "no"
      bond_mode: "active-backup"
      bond_miimon: "500"
      bond_slaves: ["{{ bond_slave_interface_1 }}", "{{ bond_slave_interface_2 }}"]
      address: "{{ admin_network_address }}"
      netmask: "255.255.0.0"
      gateway: ""

network_ether_interfaces:
    - device: "{{ management_interface }}" 
      bootproto: "static"
      onboot: "yes"
      nm_controlled: "no"
      address: "{{ management_network_address }}"
      netmask: "255.255.255.0"
      gateway: "86.50.163.1"

