---
- name: Configure admin users (potentially as root)
  hosts: common
  tags: common
  gather_facts: no
- include: add_admin_users.yml

- name: Configure the system (as current admin user)
  hosts: common 
  tags: common
  sudo: yes
  roles: 
  - common
  - ansible-role-sshd

####### cPouta Network Configuration #######

- include: cpouta-management-network.yml
- include: cpouta-admin-network.yml
- include: cpouta-ceph-network.yml

####### ePouta Network Configuration #######

- include: epouta-ceph-network.yml
