---
- hosts: common 
  sudo: yes
  tags: cpouta-ceph-network
  roles:
    - role: network_interface
      when: configure_ceph_network and node_type == "osd" and project == "cpouta"
      network_vlan_interfaces:
        - device: "{{ bonded_interface }}.{{ cluster_network_vlan_tag }}"
          vlan: "yes"
          bootproto: "static"
          nm_controlled: "no"
          address: "{{ cluster_network_address }}"
          netmask: "{{ cluster_network_netmask }}"
        - device: "{{ bonded_interface }}.{{ public_network_vlan_tag }}"
          vlan: "yes"
          bootproto: "static"
          nm_controlled: "no"
          address: "{{ public_network_address }}"
          netmask: "{{ public_network_netmask }}"

    - role: network_interface
      when: configure_ceph_network and node_type == "mon" and project == "cpouta"
      network_vlan_interfaces:
        - device: "{{ bonded_interface }}.{{ public_network_vlan_tag }}"
          vlan: "yes"
          bootproto: "static"
          nm_controlled: "no"
          address: "{{ public_network_address }}"
          netmask: "{{ public_network_netmask }}"
