---
- hosts: hardware_type_HPSL4540
  user: root
  tags: cpouta-ceph-network
  roles:
    - role: network_interface
      when: configure_ceph_network and hardware_type_HPSL4540 and project == "cpouta"
      network_vlan_interfaces:
        - device: "{{ bonded_interface }}.{{ cluster_network_vlan_tag }}"
          vlan: "yes"
          bootproto: "static"
          nm_controlled: "no"
          address: "{{ cluster_network_address }}"
          netmask: "{{ cluster_network_netmask }}"
          gateway: "{{ cluster_network_gateway }}"
        - device: "{{ bonded_interface }}.{{ public_network_vlan_tag }}"
          vlan: "yes"
          bootproto: "static"
          nm_controlled: "no"
          address: "{{ public_network_address }}"
          netmask: "{{ public_network_netmask }}"
          gateway: "{{ public_network_gateway }}"

