---
- name: Installing EPEL 
  yum: name="{{item}}" state=present
  with_items:
    - epel-release

- name: Installing Packages
  yum: name="{{item}}" state=present
  with_items:
    - htop
    - ntp
    - tree
    - perl
    - wget
    - tmux
    - glances
    - telnet
    - vim
    - dstat
    - iperf
    - fio

- include: ceph_repo_setup.yml

