---
- name: Installing EPEL 
  yum: name="{{item}}" state=present
  with_items:
    - epel-release

- include: ceph_repo_setup.yml

- include: hp_repo_setup.yml
  when: ansible_system_vendor == "HP"

